### ISSUE TITLE
you need to have proton installed or you need to export PROTON

### ISSUE THREAD

**Issue by holydrug** [Francesco149/protonfit#2]
:: ERROR: you need to have proton installed or you need to export PROTON, which defaults to /usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton

Yes it is. There is no that catalog. I enable Chaotic-AUR and install proton through 'pacman -S proton' May be i do smth bad? Any ideas?

Sorry for stupid question :(

**Comment by holydrug** [comment]
okey bois, copy all files from proton-custom to /usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/ solved all problems haha

gl all

**Comment by xBiei** [comment]
yeah you can do that or just use `export PROTON="proton_location_here"` .
(Ex: `export PROTON="~/.steam/root/compatibilitytools.d/proton_tkg/proton"`).
